

platform:
  - x64

configuration:
  - Release

before_build:
  - cmd: git submodule update --init

build:

build_script:
  - msbuild /m /p:Configuration=Release rpcs3.sln
  
after_build:
  - cmd: package.bat

artifacts:
  # pushing a single file
  - path: *.7z


test: OFF

deploy: OFF
