

# version format
version: 0.1.{build}

branches:
  only:
    - appveyorbuild
  # blacklist
  #except:
  #  - gh-pages

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# clone directory
clone_folder: c:\projects\rpcs3

platform:
  - x64

configuration:
  - Release

install:
  - cmd: cinst wget -x86
  - cmd: cinst 7zip.commandline -x86
  - cmd: git submodule update --init --recursive .\ffmpeg .\asmjit
  - cmd: wget --no-check-certificate https://googledrive.com/host/0B3tDmChwjRbRTTdhaTFOeGN1eEU/wxWidgets.7z -O c:\projects\rpcs3\wxwidgets.7z
  - cmd: mkdir c:\projects\rpcs3\wxWidgets
  - cmd: 7z x C:\projects\rpcs3\wxwidgets.7z -oc:\projects\rpcs3\
  
build:

build_script:
  - msbuild /m /p:Configuration=Release rpcs3.sln
  
after_build:
  - cmd: package.bat

artifacts:
  - path: .\*.7z

deploy:
  - provider: FTP
    server: 
      secure: kZT7rsbEPGQ0fC2GFRBGfL2vPwUgih2JkwjbSuw00T8=
    username:
      secure: YJzwsi4wfSezFLqaB9uiww==
    password:
      secure: EQ3xa2LoRgelAdE57+qakQ==
    folder: .\rpcs3\
    enable_ssl: false
  
test: OFF

